server:
    port: 8081
    address: 0.0.0.0

spring:
    liquibase:
        enabled: true
        change-log: classpath:db/changelog/db.changelog-master.yaml
        default-schema: public

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/SafeVision
        username: postgres
        password: 12345
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 20MB
            enabled: true
SafeVision:
    patterns:
        dateTimePattern: yyyy-MM-dd HH:mm